"""empty message

Revision ID: 2c476376f1a4
Revises: cf44390a14f1
Create Date: 2020-08-08 18:41:11.489787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c476376f1a4'
down_revision = 'cf44390a14f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dishes', 'categories', ['category_id'], ['id'])
    op.add_column('orders', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'user_id')
    op.drop_constraint(None, 'dishes', type_='foreignkey')
    op.drop_column('dishes', 'category_id')
    # ### end Alembic commands ###
