"""empty message

Revision ID: 74bed44aff19
Revises: 2eed1b6b0068
Create Date: 2020-08-11 10:12:36.472625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74bed44aff19'
down_revision = '2eed1b6b0068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_date', sa.Date(), nullable=False))
    op.drop_column('orders', 'status')
    op.drop_column('orders', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('orders', 'order_date')
    # ### end Alembic commands ###
