"""empty message

Revision ID: 805208069550
Revises: 74bed44aff19
Create Date: 2020-08-12 19:27:28.799572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '805208069550'
down_revision = '74bed44aff19'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("""
    ALTER TABLE users
    RENAME COLUMN password TO password_hash""")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
